deploy_dev:
    stage: deploy
    tags:
        - dev
    script:
        - rsync -ua $CI_PROJECT_DIR/* $DEV_PROJECT_DIR/
        - chown -R portfolio:webusers $DEV_PROJECT_DIR
    environment:
        name: development
        url: google.com
    only:
        - dev